# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on Windows x86_64 using MSYS2-clang64

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64
        update: true
        install: git mingw-w64-clang-x86_64-toolchain mingw-w64-clang-x86_64-glfw mingw-w64-clang-x86_64-cmake mingw-w64-clang-x86_64-freetype
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config MinSizeRel --parallel

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Deckadence.exe
        path: ${{github.workspace}}/build/Deckadence.exe
        if-no-files-found: error
